#!/bin/sh -e

#!/bin/sh
NAME=tier4-camera-gmsl
VERSION=1.2.1
KERNEL_REL=$(uname -r)
set -e
case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $NAME -v $VERSION --all
         rm -rf /usr/src/$NAME-$VERSION
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-isx021.ko
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-imx490.ko
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-max9295.ko
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-max9296.ko
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-gw5300.ko
         rm -f /lib/modules/$KERNEL_REL/updates/dkms/tier4-fpga.ko
         rm -f /lib/firmware/tier4-isx021.bin
         rm -f /etc/modules-load.d/tier4-imx490-gmsl.conf
         rm -f /etc/modules-load.d/tier4-isx021-gmsl.conf
         rm -f /etc/modprobe.d/tier4-isx021.conf
         rm -f /etc/modprobe.d/tier4-imx490.conf
         rm -rf /boot/tier4-isx021-gmsl-device-tree-overlay.dtbo
         rm -rf /boot/tier4-isx021-gmsl-device-tree-overlay-orin.dtbo
         rm -rf /boot/tier4-imx490-gmsl-device-tree-overlay.dtbo
         rm -rf /boot/tier4-imx490-gmsl-device-tree-overlay-orin.dtbo
         rm -rf /boot/tier4-isx021-imx490-gmsl-device-tree-overlay.dtbo
         rm -rf /boot/tier4-isx021-imx490-gmsl-device-tree-overlay-orin.dtbo
      fi
    ;;

    failed-upgrade)
    ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
exit 0
